const CartActionTypes = {
	TOGGLE_HIDDEN_CART: 'TOGGLE_HIDDEN_CART',
	ADD_ITEM_TO_CART: 'ADD_ITEM_TO_CART',
	REMOVE_ITEM_FROM_CART: 'REMOVE_ITEM_FROM_CART',
	REMOVE_ITEM: 'REMOVE_ITEM'
}


export default CartActionTypes